# Generated by Django 3.1.1 on 2020-10-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20201006_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
